#!/bin/sh

RN=/home/esm/src/atomic/2018-02.podman/cri-o/build/bin/release-notes

$RN --org=containers --repo=podman \
    --branch=main \
    --repo-path=/var/tmp/pmpm \
    --required-author= \
    --start-sha=e47dda5d81772fcc1c2417062303681a72780bbd \
    --end-sha=2e9f792e378491acc3c04ba389ec7cf15bef471e \
    --output=/tmp/esm-esm.md \
    --toc


# --required-author= --start-rev=v1.22.0 --end-sha=7e218a36eb7c48c6d0f5de65523e238b04f2b313 --output=/home/esm/src/atomic/2017-09.cri-o/cri-o/build/release-notes/v1.23.0.md --toc --go-template=go-template:/dev/shm/258053125
